fiat/blueprints/webui/__init__.py
from flask import Blueprint

from .views import index, carro

bp = Blueprint("webui", __name__, template_folder="templates")

bp.add_url_rule("/", view_func=index, endpoint="index")
bp.add_url_rule("/carro/<placa>", view_func=carro, endpoint="carroview")


def init_app(app):
    app.register_blueprint(bp)

fiat/blueprints/webui/views.py
from flask import abort, render_template
from fiat.models import Fiatdata


def index():
    carros = Fiatdata.query.all()
    return render_template("index.html", carros=carros)


def carro(placa):
    carro = Fiatdata.query.filter_by(placa=placa).first() or abort(
        404, "Carro nao encontrado"
    )
    return render_template("carro.html", carro=carro)

fiat/blueprints/webui/templates/carro.html
{% extends "index.html" %}
{% block content %}
<style>
    body {
        background-color: #333;
        /* Cor de fundo escura para toda a página */
        color: #635b5b;
        /* Cor do texto branca para toda a página */
    }

    .navbar {
        background-color: #333;
        /* Cor de fundo escura para a navbar */
    }

    .navbar a {
        color: #5f5959db;
        /* Cor do texto branco para os links da navbar */
    }

    /* Estilo escuro para os botões */
    .btn-dark {
        background-color: #333;
        /* Cor de fundo escura para os botões */
        color: #fff;
        /* Cor do texto branca para os botões */
    }

    .btn-dark:hover {
        background-color: #555;
        /* Cor de fundo mais escura quando o botão é hover */
    }
</style>

<div class="container">
    <div class="jumbotron">
        <h1 class="display-4">Nome: {{ carro.nome }}</h1>
        <h2 class="display-5">Placa: {{ carro.placa }}</h2>
        <p class="lead">Detalhe: {{ carro.detalhe }}</p>
        <p class="lead">Preço: {{ carro.preco }}</p>
    </div>
</div>
{% endblock %}

fiat/blueprints/webui/templates/index.html
{% extends "bootstrap/base.html" %}
{% block title %}{{config.get('TITLE')}}{% endblock %}

{% block navbar %}
<div class="navbar">
    <div class="navbar-header">
        <a class="navbar-brand" href="{{url_for('webui.index')}}">
            <img alt="Brand"
                src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAB+0lEQVR4AcyYg5LkUBhG+1X2PdZGaW3btm3btm3bHttWrPomd1r/2Jn/VJ02TpxcH4CQ/dsuazWgzbIdrm9dZVd4pBz4zx2igTaFHrhvjneVXNHCSqIlFEjiwMyyyOBilRgGSqLNF1jnwNQdIvAt48C3IlBmHCiLQHC2zoHDu6zG1iXn6+y62ScxY9AODO6w0pvAqf23oSE4joOfH6OxfMoRnoGUm+de8wykbFt6wZtA07QwtNOqKh3ZbS3Wzz2F+1c/QJY0UCJ/J3kXWJfv7VhxCRRV1jGw7XI+gcO7rEFFRvdYxydwcPsVsC0bQdKScngt4iUTD4Fy/8p7PoHzRu1DclwmgmiqgUXjD3oTKHbAt869qdJ7l98jNTEblPTkXMwetpvnftA0LLHb4X8kiY9Kx6Q+W7wJtG0HR7fdrtYz+x7iya0vkEtUULIzCjC21wY+W/GYXusRH5kGytWTLxgEEhePPwhKYb7EK3BQuxWwTBuUkd3X8goUn6fMHLyTT+DCsQdAEXNzSMeVPAJHdF2DmH8poCREp3uwm7HsGq9J9q69iuunX6EgrwQVObjpBt8z6rdPfvE8kiiyhsvHnomrQx6BxYUyYiNS8f75H1w4/ISepDZLoDhNJ9cdNUquhRsv+6EP9oNH7Iff2A9g8h8CLt1gH0Qf9NMQAFnO60BJFQe0AAAAAElFTkSuQmCC">
        </a>
    </div>

</div>
{% endblock %}

{% block content %}
<style>
    body {
        background-color: #333;
        /* Cor de fundo escura para toda a página */
        color: #fff;
        /* Cor do texto branca para toda a página */
    }

    .navbar {
        background-color: #333;
        /* Cor de fundo escura para a navbar */
    }

    .navbar a {
        color: #fff;
        /* Cor do texto branco para os links da navbar */
    }

    /* Estilo escuro para os botões */
    .btn-dark {
        background-color: #333;
        /* Cor de fundo escura para os botões */
        color: #fff;
        /* Cor do texto branca para os botões */
    }

    .btn-dark:hover {
        background-color: #555;
        /* Cor de fundo mais escura quando o botão é hover */
    }
</style>
<div class="container">
    <h1>{{config.get('TITLE')}}</h1>

    <div class="jumbotron">
        <ul class="list-group">
            {% for carro in carros %}
            <li class="list-group-item">
                <a href="{{url_for('webui.carroview', placa=carro.placa)}}">{{carro.placa}}- {{carro.nome}}</a>
            </li>
            {% endfor %}
        </ul>
    </div>

</div>
{% endblock %}